server {
	listen 80;
	server_name 47.236.240.233;

	location / {
		root /home/innowing/umag/frontend/dist/;
	}		

	location /api/ {
		proxy_pass http://127.0.0.1:8003/api/;	
		proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_buffering off;	
	}
	
	location /static/ {
		proxy_pass http://127.0.0.1:8003/static/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
	

	location /langgraph/ {		
		proxy_pass http://127.0.0.1:2024/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

}
server {
	listen 2025;
	server_name 47.236.240.233;

	location / {		
		proxy_pass http://127.0.0.1:2024/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
}


 # zrok2 agent
 server {
	 listen 8889;
         server_name 47.236.240.233;	

	 location / {
		 proxy_pass http://127.0.0.1:8888/;
		 proxy_set_header Host $host;
		 proxy_set_header X-Real-IP $remote_addr;
		 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

	 }
 }
